### ISSUE TITLE
[KiField Feature Request] No-range flag for spreadsheet output

### ISSUE THREAD

**Issue by scandey** [devbisme/KiField#70]
**Is your feature request related to a problem? Please describe.**

I search BOMs (and Kifield spreadsheets) by arbitrary reference designators using CTRL-F, and I want to guarantee that if a reference designator exists in the grouped Kifield spreadsheet, it will be found. Currently the behavior of the workbook writer, prior to csv or xlsx output, is to collapse a group of reference designators into ranges like `C1-C3, C8`. This is good for concise reading, but makes casually searching for C2 difficult.  

**Describe the solution you'd like**
Add a new flag `--no_range` or `-nr`, which disables hyphenated ranges and explicitly shows each component reference in a group.

**Additional context**
Origin in the the unrelated [issue 60](https://github.com/devbisme/KiField/issues/60)

**Comment by devbisme** [comment]
Released in version 0.2.0. Thanks!
